### ISSUE TITLE
Question about normalization

### ISSUE THREAD

**Issue by jsshin98** [junleen/RainNet#10]
Is there any specific reason why discriminator process both spectral and instance normalization on the forward function? 
Based on the paper, it only covers spectral normalization for discriminator network.

**Comment by junleen** [comment]
Thanks. Spectral Normalization is employed in GAN training for stabilizing the discriminator. And instance normalization in the discriminator is a trivial setting in reference work(DoveNet). We just keep the same normalization method as it uses.
