### ISSUE TITLE
测试结果与论文不同

### ISSUE THREAD

**Issue by sqj1234** [junleen/RainNet#15]
可以问一下你的环境设置吗？我用你的预训练模型得不到论文中的结果

**Comment by junleen** [comment]
之前有一个大佬也碰到了这样的问题，可能是训练和测试时版本的问题，你参考这个 #2

**Comment by sqj1234** [comment]
我改到1.7.0，MSE还是54

**Comment by junleen** [comment]
我不确定唉，你对图片做什么处理了吗？
