### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by hoangtnm** [junleen/RainNet#18]
Hi, I have downloaded the iHarmony4 dataset and extract it, but when I run the script `python data/preprocess_iharmony4.py --dir_iharmony4 <DIR_of_iHarmony4> --save_dir <SAVE_DIR> --image_size <IMAGE_SIZE>`, it raises

```
Traceback (most recent call last):
  File "data/preprocess_iharmony4.py", line 22, in <module>
    with open(os.path.join(args.dir_iharmony4, 'IHD_train.txt'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../datasets/iHarmony4/IHD_train.txt'
```

I have searched through the [dataset](https://cloud.bcmi.sjtu.edu.cn/fsdownload/CCExSuoDA/Image_Harmonization_Dataset) but the file `IHD_train.txt` is not found.

**Comment by hoangtnm** [comment]
It looks like that that `IHD_train.txt` and `IHD_test.txt` is only available on [Baidu link](https://pan.baidu.com/s/1xEN0Xrv_MbuKT0ZqsipeEg) but not [Alternative_address](https://cloud.bcmi.sjtu.edu.cn/sharing/CCExSuoDA). But I don't have baidu account, so can you share a link to those files outside Baidu, thank you?

**Comment by zhanghongyong123456** [comment]
> It looks like that that `IHD_train.txt` and `IHD_test.txt` is only available on [Baidu link](https://pan.baidu.com/s/1xEN0Xrv_MbuKT0ZqsipeEg) but not [Alternative_address](https://cloud.bcmi.sjtu.edu.cn/sharing/CCExSuoDA). But I don't have baidu account, so can you share a link to those files outside Baidu, thank you?

[IHD_test.txt](https://github.com/junleen/RainNet/files/7622730/IHD_test.txt)
[IHD_train.txt](https://github.com/junleen/RainNet/files/7622732/IHD_train.txt)
