### ISSUE TITLE
关于训练流程

### ISSUE THREAD

**Issue by XavierYu404** [junleen/RainNet#22]
您好，是每个batch都更新一下鉴别器和生成器嘛？我按照这样的方式训练好像无法收敛诶，MSE无法降下来

**Comment by junleen** [comment]
> 您好，是每个batch都更新一下鉴别器和生成器嘛？我按照这样的方式训练好像无法收敛诶，MSE无法降下来

是一次D一次G
MSE不会不降的吧，我反复训练过几次，没有出现MSE降不下来的情况

**Comment by XavierYu404** [comment]
呜哇 感谢您的回复，
mse是从一开始就持续下降得嘛 ？ 还是要到后面才会降下来
我用10k张图作为训练集，3k张作为验证集，60多个epoch的时候mse还是没下来，一直在上下跳
我只把batch_size改成了40，别的参数我没改，是不是我漏调一些参数啊
