### ISSUE TITLE
关于test.py的问题

### ISSUE THREAD

**Issue by Jerent** [junleen/RainNet#3]
我按照指导，尝试用test.py验证附件中/examples/1.png等，但是报错中提示我Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
![2021-07-22 18-10-35 的屏幕截图](https://user-images.githubusercontent.com/67627350/126623489-a9ae2e03-887c-4d24-8be0-a92c35faf979.png)
请问有人遇到过相似的问题吗

**Comment by junleen** [comment]
这是数据和模型所在的设备不一致导致的，尝试改变两个部分，
1. 改模型加载：
```python
把test.py里面的:
state_dict = torch.load(load_path)
改为:
state_dict = torch.load(load_path, map_location='cpu')
```
2. `__main__`部分：
把rainnet放置在cuda上，
```python
在test.py的line30后添加 rainnet = rainnet.to(device)
```

**Comment by Jerent** [comment]
这个改动很好地解决了问题，感谢！
