### ISSUE TITLE
论文中的PSNR结果是4个数据集一起训练得到的结果还是各自独立训练得到的结果

### ISSUE THREAD

**Issue by liuzurang** [junleen/RainNet#4]
您好，我最近在学习这篇论文，有几个问题想请教：
1. 仓库中只提供了一个checkpoint文件，是4个数据集一起训练的结果吗？
2. 想确认一下论文中table 1的结果是独立训练得到的结果还是一起训练得到的结果呢？
感谢！

**Comment by junleen** [comment]
是一起训练的呢

**Comment by junleen** [comment]
在四个子数据集上测，把结果分开展示了。这一点跟那个数据集对应的论文处理方式是一样的

**Comment by liuzurang** [comment]
好咧，学习了，感谢！
