### ISSUE TITLE
Testing the model with images of arbitrary resolution

### ISSUE THREAD

**Issue by HaozhouPang** [junleen/RainNet#6]
Hi, thank you for posting this great work!

I am wondering is it possible to test the model with images of arbitrary resolution?

**Comment by junleen** [comment]
Probably not!

**Comment by HaozhouPang** [comment]
Thanks for the reply! 

I am closing this issue with some of my findings. One way to test the model with 'non-square' images is resizing your input to a multiple of 256 and modifying the 'load_size' in test_dataset accordingly. You will not encounter dimension errors in this way, but the result might degrade as the model was originally trained by squared images of fixed resolution.

Best.

**Comment by dreamer121121** [comment]
I found that the generated harmony image will be low-resolution and has some noise，have u met the same problem?
